workflows:
    simulator-native-ios:
        name: iOS simulator build
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
               XCODE_WORKSPACE: "AimyboxUI.xcworkspace" # <-- Put the name of your Xcode workspace here
               XCODE_SCHEME: "AimyboxUI" # <-- Put the name of your Xcode scheme here
            xcode: 13.0
            cocoapods: default
        scripts:
            - name: Install CocoaPods dependencies
              script: |
                                pod install
            - name: Build ipa for distribution
              script: |
               - xcode-project build-ipa --project "MyXcodeProject.xcodeproj" --scheme "MyScheme"
       
       artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

